### ISSUE TITLE
Act 8 Documento ERS

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-osteas-b#1]
https://github.com/SistemasTecTlaxiaco/ChainProtec/wiki

**Comment by williamgl3** [comment]
29/30 faltan requisistos del sistema

**Comment by josealfredo79** [comment]
Definir bien los objetivos del sistema, los casos de usos...etc.

**Comment by josealfredo79** [comment]
Bien hecho y revisado....
